### ISSUE TITLE
Include field for metadata

### ISSUE THREAD

**Issue by malik672** [foundry-rs/compilers#110]
in the bytecode.rs file, i think the Bytecode struct should contain an optional field for the contract metadata

**Comment by klkvr** [comment]
Metadata is [kept](https://github.com/foundry-rs/compilers/blob/3f080851e3a38a2a3e867f92173d85449aa07fb4/crates/artifacts/solc/src/configurable.rs#L38) directly on artiract and is not part of the bytecode object returned by Solidity https://docs.soliditylang.org/en/latest/using-the-compiler.html#input-description

Closing as metadata can be accessed from existing artifacts and is at a right place IMO
