### ISSUE TITLE
Searching for the new equivalent of `Solc::detect_version(..)`

### ISSUE THREAD

**Issue by TilakMaddy** [foundry-rs/compilers#119]
I'm looking for the new equivalent of `Solc::detect_version(..)` 

Additional Context
It was there in 0.3.0 but not in 0.4.0 which is breaking some changes for [aderyn's](https://github.com/Cyfrin/aderyn)

**Comment by mattsse** [comment]
thanks for flagging, we refactored a bunch of stuff and a lot of install handling was moved to SolcVersionManager

I've added the `detect_version` fn back because this is still useful.

there are likely still some inconveniences, so please lmk if you think something could be improved
