### ISSUE TITLE
README example is outdated / doesn't compile

### ISSUE THREAD

**Issue by DaniPopes** [foundry-rs/compilers#168]
1. Needs to point to crates.io
2. Needs either updating the instantiation of project or implementing Default for MultiCompiler
3. Hook it up to rustdoc through symlinks and  `#![doc = include_str!("../README.md")]`

**Comment by klkvr** [comment]
`Default` is implemented for `MultiCompiler` with `svm-solc`, most of our doctests assume it's enabled. perhaps we should remove this feature at this point? I believe it is not that heavy, but makes working with compilers pretty convenient
