### ISSUE TITLE
Add sourcelist to compilation artifacts

### ISSUE THREAD

**Issue by JoranHonig** [foundry-rs/compilers#182]
### Component

Forge

### Describe the feature you would like

The new compilation artifacts have almost all the necessary information needed for downstream tools to work with forges' compilation artifacts.

The one thing that's missing is the solc sourcelist, this provides a mapping from file indices to file names. This is necessary when you want to map a bytecode location to a source location in a solidity file.

**Comment by klkvr** [comment]
After https://github.com/foundry-rs/compilers/pull/140 cache now keeps a mapping `source -> build` where each build keeps a list of source ids, which match those appearing in sourcemaps
