### ISSUE TITLE
Flattening generates invalid solidity contract

### ISSUE THREAD

**Issue by crystalin** [foundry-rs/compilers#183]
If you retrieve solidity files from ethereum `0xbe9895146f7af43049ca1c1ae358b0541ea49704` and try to flatten the mainfile `centre-tokens/contracts/v1/FiatTokenProxy.sol` the output starts with:

```
* SPDX-License-Identifier: MIT
pragma solidity =0.6.12 ^0.6.2;

// @openzeppelin/contracts/utils/Address.sol

/**
 * @dev Collection of functions related to the address type
 */
library Address {
```

Which is invalid due to the `* SPDX-License-Identifier: MIT` which has been separated from the /** ... **/ lines
I'm not sure if this is due to pragma removal or import injections but something is weird (also in other imported sources, it is missing the 2nd line of the file)

`forge flatten centre-tokens/contracts/v1/FiatTokenProxy.sol`

I included the files: [0xbe9895146f7af43049ca1c1ae358b0541ea49704.tar.gz](https://github.com/user-attachments/files/16470341/0xbe9895146f7af43049ca1c1ae358b0541ea49704.tar.gz)

**Comment by DaniPopes** [comment]
cc @klkvr
