### ISSUE TITLE
Improve incompatible solidity versions error formatting

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/compilers#43]
ref https://github.com/foundry-rs/foundry/issues/6722

this should improve error formatting and ideally highlight the conflicting versions

https://github.com/foundry-rs/compilers/blob/314c9171c3c09a90dd528c4884bc1b3da569308b/src/resolver/mod.rs#L607-L609

**Comment by AbhinavMir** [comment]
would love to take this on sometime this week. :)

**Comment by AbhinavMir** [comment]
@mattsse How do I get `foundry_compilers` to throw errors when compiling faulty code? I wrote a Solidity code with syntax errors, and expect it to fail, but `foundry_compilers` compiles it.

```rust
use foundry_compilers::{Project, ProjectPathsConfig};

fn main() {
    let project = Project::builder()
        .paths(ProjectPathsConfig::hardhat("/home/august/bad_code_solidity_hardhat").unwrap())
        .build()
        .unwrap();

    if let Err(e) = project.compile() {
        // The compilation failed, `e` contains the error.
        eprintln!("Compilation failed with error: {:?}", e);
    }

    project.rerun_if_sources_changed();
}
```
