### ISSUE TITLE
feat: `Cancun` EVM version

### ISSUE THREAD

**Issue by clabby** [foundry-rs/compilers#46]
## Overview

`solc` recently added `Cancun` as an EVM version in `EVMVersion.h` [here](https://github.com/ethereum/solidity/blob/develop/liblangutil/EVMVersion.h#L62). `EVMVersions`' doc comment [calls for syncing up](https://github.com/foundry-rs/compilers/blob/6528e4ac0b8f17599fd4b6b1e091b21c690ad142/src/artifacts/mod.rs#L781), which will unblock further support in `foundry`.

**Comment by mattsse** [comment]
ref https://github.com/foundry-rs/compilers/blob/a420980485681d303c80519eb4dbedbe0caee899/src/artifacts/mod.rs#L783
